// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3YOnohUHlNa72WeGnYlmu7lYs1uDAF4',
    appId: '1:900617898161:web:5dd0249a21779b26af3a90',
    messagingSenderId: '900617898161',
    projectId: 'skillswap-79be8',
    authDomain: 'skillswap-79be8.firebaseapp.com',
    storageBucket: 'skillswap-79be8.firebasestorage.app',
    measurementId: 'G-DHXBVYFGGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZx0jytT4cKRLi63zE4hej0gzrMtKDr6M',
    appId: '1:900617898161:android:d7969815ddd43355af3a90',
    messagingSenderId: '900617898161',
    projectId: 'skillswap-79be8',
    storageBucket: 'skillswap-79be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5XSl1nQOZk_bsQJuPV5DT1AN3_xs28E',
    appId: '1:900617898161:ios:51918b3692c1c77caf3a90',
    messagingSenderId: '900617898161',
    projectId: 'skillswap-79be8',
    storageBucket: 'skillswap-79be8.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm5XSl1nQOZk_bsQJuPV5DT1AN3_xs28E',
    appId: '1:900617898161:ios:51918b3692c1c77caf3a90',
    messagingSenderId: '900617898161',
    projectId: 'skillswap-79be8',
    storageBucket: 'skillswap-79be8.firebasestorage.app',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd3YOnohUHlNa72WeGnYlmu7lYs1uDAF4',
    appId: '1:900617898161:web:b676536b9aa04969af3a90',
    messagingSenderId: '900617898161',
    projectId: 'skillswap-79be8',
    authDomain: 'skillswap-79be8.firebaseapp.com',
    storageBucket: 'skillswap-79be8.firebasestorage.app',
    measurementId: 'G-H4QV2BN9H3',
  );
}
